// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WellSensorAnalytics.Data;

#nullable disable

namespace WellSensorAnalytics.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20250828074155_NamingAndStartEndResTime")]
    partial class NamingAndStartEndResTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WellSensorAnalytics.Models.Entities.Algorithm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'utc'");

                    b.Property<DateTimeOffset?>("LastRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run");

                    b.Property<TimeSpan>("LookbackInterval")
                        .HasColumnType("interval")
                        .HasColumnName("lookback_interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(127)")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("ScheduleInterval")
                        .HasColumnType("interval")
                        .HasColumnName("schedule_interval");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<int>("WaterWellId")
                        .HasColumnType("integer")
                        .HasColumnName("water_well_id");

                    b.HasKey("Id")
                        .HasName("pk_algorithm");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_algorithm_enabled");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_algorithm_name");

                    b.ToTable("algorithm", (string)null);
                });

            modelBuilder.Entity("WellSensorAnalytics.Models.Entities.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmId")
                        .HasColumnType("integer")
                        .HasColumnName("algorithm_id");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_timestamp");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("StartTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_analysis_result");

                    b.HasIndex("AlgorithmId")
                        .HasDatabaseName("ix_analysis_result_algorithm_id");

                    b.ToTable("analysis_result", (string)null);
                });

            modelBuilder.Entity("WellSensorAnalytics.Models.Entities.AnalysisResult", b =>
                {
                    b.HasOne("WellSensorAnalytics.Models.Entities.Algorithm", "Algorithm")
                        .WithMany()
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_result_algorithm_algorithm_id");

                    b.Navigation("Algorithm");
                });
#pragma warning restore 612, 618
        }
    }
}
